export const TABS = [
  {
    id: 'C003',
    label: '제품 목록',
    description: [
      '식약처에 신고된 건강기능식품 제품 전체 목록 (44,000+건)',
      '검색어를 입력하면 서버에서 필터링된 결과만 가져옵니다',
    ],
    columns: [
      { key: 'PRDLST_REPORT_NO', label: '품목신고번호', defaultOn: true },
      { key: 'PRDLST_NM', label: '제품명', defaultOn: true },
      { key: 'BSSH_NM', label: '업체명', defaultOn: true },
      { key: 'PRMS_DT', label: '신고일자', defaultOn: true },
      { key: 'PRDT_SHAP_CD_NM', label: '제형', desc: '정제/캡슐/분말/액상 등 제품 형태' },
      { key: 'PRIMARY_FNCLTY', label: '기능성', desc: '해당 제품의 기능성 표시 내용' },
      { key: 'RAWMTRL_NM', label: '원재료', desc: '기능성 원료 + 부원료 전체 텍스트' },
      { key: 'NTK_MTHD', label: '섭취방법', desc: '1일 섭취량 및 섭취 방법' },
      { key: 'IFTKN_ATNT_MATR_CN', label: '주의사항', desc: '섭취 시 주의사항' },
      { key: 'POG_DAYCNT', label: '유통기한', desc: '유통기한 정보' },
      { key: 'LAST_UPDT_DTM', label: '최종수정일', desc: '데이터 최종 업데이트 일자' },
      { key: 'LCNS_NO', label: '인허가번호', desc: '제품 인허가 고유번호' },
      { key: 'STDR_STND', label: '기준규격', desc: '성분 함량 기준 및 시험법' },
      { key: 'DISPOS', label: '성상', desc: '제품 외형 설명 (색상, 형태 등)' },
      { key: 'CSTDY_MTHD', label: '보관방법', desc: '냉장/실온 등 보관 조건' },
      { key: 'CRET_DTM', label: '데이터 생성일', desc: '데이터가 처음 등록된 일자' },
    ],
    dateField: 'PRMS_DT',
    dateLabel: 'NEW',
    serverFilterFields: [
      { key: 'PRDLST_NM', label: '제품명' },
      { key: 'BSSH_NM', label: '업체명' },
      { key: 'RAWMTRL_NM', label: '원재료' },
    ],
    searchFields: ['PRDLST_NM', 'BSSH_NM', 'PRIMARY_FNCLTY', 'RAWMTRL_NM'],
    useServerFilter: true,
  },
  {
    id: 'I2710',
    label: '고시형 원료',
    description: [
      '식약처가 공식 허가한 건강기능식품 원료 목록 (521건)',
      'R&D 및 인허가 팀의 원료 기초 데이터로 활용',
    ],
    columns: [
      { key: 'PRDCT_NM', label: '원료명', defaultOn: true },
      { key: 'PRIMARY_FNCLTY', label: '기능성', defaultOn: true },
      { key: 'DAY_INTK_LOWLIMIT', label: '일일섭취량 하한', desc: '하루 최소 섭취량' },
      { key: 'DAY_INTK_HIGHLIMIT', label: '일일섭취량 상한', desc: '하루 최대 섭취량' },
      { key: 'INTK_UNIT', label: '단위', desc: '섭취량 단위 (mg, g 등)' },
      { key: 'IFTKN_ATNT_MATR_CN', label: '주의사항', desc: '섭취 시 주의사항' },
      { key: 'INTK_MEMO', label: '섭취 메모', desc: '추가 섭취 안내사항' },
      { key: 'SKLL_IX_IRDNT_RAWMTRL', label: '지표성분', desc: '기능성 지표 원료명' },
      { key: 'LAST_UPDT_DTM', label: '최종수정일', desc: '데이터 최종 업데이트 일자' },
      { key: 'CRET_DTM', label: '데이터 생성일', desc: '데이터가 처음 등록된 일자' },
    ],
    dateField: 'LAST_UPDT_DTM',
    dateLabel: '수정됨',
    searchFields: ['PRDCT_NM', 'PRIMARY_FNCLTY'],
    useServerFilter: false,
  },
  {
    id: 'I-0040',
    label: '기능성 원료 인정',
    description: [
      '업체가 신청하여 식약처에서 기능성을 공식 인정받은 원료 목록 (751건)',
      '인허가 전략 수립 및 경쟁사 원료 동향 파악에 활용',
    ],
    columns: [
      { key: 'APLC_RAWMTRL_NM', label: '원료명', defaultOn: true },
      { key: 'BSSH_NM', label: '신청업체', defaultOn: true },
      { key: 'PRMS_DT', label: '인정일자', defaultOn: true },
      { key: 'HF_FNCLTY_MTRAL_RCOGN_NO', label: '인정번호', desc: '기능성 원료 인정 고유번호' },
      { key: 'FNCLTY_CN', label: '기능성 내용', desc: '식약처 인정 기능성 표시 문구' },
      { key: 'DAY_INTK_CN', label: '일일섭취량', desc: '인정된 일일 섭취량 기준' },
      { key: 'IFTKN_ATNT_MATR_CN', label: '주의사항', desc: '섭취 시 주의사항' },
      { key: 'INDUTY_NM', label: '업종', desc: '제조업 / 수입업 구분' },
      { key: 'ADDR', label: '주소', desc: '신청업체 주소' },
    ],
    dateField: 'PRMS_DT',
    dateLabel: 'NEW',
    searchFields: ['APLC_RAWMTRL_NM', 'BSSH_NM', 'FNCLTY_CN'],
    useServerFilter: false,
  },
  {
    id: 'I-0050',
    label: '개별인정형 원료',
    description: [
      '개별 심사를 통해 식약처 인정을 받은 기능성 원료 목록 (423건)',
      '인허가 번호 기반 원료 추적 및 기능성 범위 확인에 활용',
    ],
    columns: [
      { key: 'RAWMTRL_NM', label: '원료명', defaultOn: true },
      { key: 'HF_FNCLTY_MTRAL_RCOGN_NO', label: '인정번호', defaultOn: true },
      { key: 'PRIMARY_FNCLTY', label: '기능성', desc: '인정된 기능성 내용 (국문/영문)' },
      { key: 'DAY_INTK_LOWLIMIT', label: '섭취량 하한', desc: '하루 최소 섭취량' },
      { key: 'DAY_INTK_HIGHLIMIT', label: '섭취량 상한', desc: '하루 최대 섭취량' },
      { key: 'WT_UNIT', label: '단위', desc: '섭취량 단위' },
      { key: 'IFTKN_ATNT_MATR_CN', label: '주의사항', desc: '섭취 시 주의사항' },
    ],
    dateField: null,
    searchFields: ['RAWMTRL_NM', 'PRIMARY_FNCLTY', 'HF_FNCLTY_MTRAL_RCOGN_NO'],
    useServerFilter: false,
  },
  {
    id: 'nutrient-analysis',
    label: '성분 함량 분석',
    description: [
      '식약처에 신고된 건강기능식품 제품 전체 목록 (44,000+건)의 영양소별 함량을 분석합니다',
      '25개 영양성분의 RDA 대비 함량을 색상으로 구분하고, 기타 기능성원료도 함께 표시합니다',
    ],
    customComponent: true,
    sourceEndpoint: 'C003',
    serverFilterFields: [
      { key: 'PRDLST_NM', label: '제품명' },
      { key: 'BSSH_NM', label: '업체명' },
      { key: 'RAWMTRL_NM', label: '원재료' },
    ],
    useServerFilter: true,
  },
]
